version: "3"

services:
  app:
    build: .
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=estoquedb
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=estoquedb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
